# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e442623881a0467f3decf918d57e10abe6058619a63e26969297ab3019cd31426c0159078b8cbe43d8e0c7d9f621df282fb62ecbaf3159edfe0542b3bdddee7

test:
  secret_key_base: 17b0c98900595353074954de36d84c70257ffd7ab1b697e5c2202c5ad9224c41e1b52ad8fe30754ddf4fb65965c14c938844893c5bd25f554a0fd988bc5d1352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
